### ISSUE TITLE
Game Name in text on Inventory page

### ISSUE THREAD

**Issue by Elinea** [SteamEP/SteamEP#8]
It would be nice to have the game name in text on the Inventory page. That way I could just use ctrl-F and type in the game name to jump right to it. Right now to avoid scrolling, I have to ctrl-F on a specific card name. 

Just a minor inconvenience but still it would be nice to have :)

As always thanks for maintaining the site and I look forwards to using it a bunch this holiday sale

See http://steamcommunity.com/groups/steam-exchange-point/discussions/0/619573787468943612/

**Comment by jclevesque** [comment]
That would be very useful.

**Comment by mtricht** [comment]
https://github.com/SteamEP/SteamEP/commit/cbe3a84c140bc24cb88caa19db48403fc6e1d185
