### ISSUE TITLE
Clean up list of cards

### ISSUE THREAD

**Issue by Elinea** [SteamEP/SteamEP#9]
Not sure how to explain this, so I'll just give an image:

http://i.imgur.com/UT5IdNo.png

Hard as hell to read, I'm not fully sure how you'd fix it though, and it all depends on what you're willing to do (CSS, JS< etc.) but at the very least I'd add a new line between Last Update and Needs, and Needs and Has. I'd also bold Status, Last updated, Needs, and Has.

See http://steamcommunity.com/groups/steam-exchange-point/discussions/0/37470848709494415/

**Comment by mtricht** [comment]
https://github.com/SteamEP/SteamEP/commit/0e7a017c144ed8b223f032c3c5fafd16a2694db5
